security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        in_memory: { memory: ~ }
        # admin_area:
        #     entity: { class: App\Entity\Admin, property: username}
        user_area:
            entity: { class: App\Entity\User }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        # admin_area:
        #     context: my
        #     security: true
        #     anonymous: true
        #     provider: admin_area
        #     form_login: 
        #         check_path: login
        #         login_path: login
        #     logout:
        #         path: /logout
        #         target: /
       
        user_area:
            context: my
            security: true
            anonymous: true
            provider: user_area
            form_login: 
                check_path: login
                login_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /
    encoders:
        # App\Entity\admin:
        #     algorithm: bcrypt
        App\Entity\User:
            algorithm: bcrypt
      

           
    access_control:
        #   - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
          - { path: ^/blog, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
